Allow astilectron to start by itself.
asticode/astilectron pull request #22
Opened 2019-08-07 19:35 UTC by sbrow

This PR allows astilectron to be started separately from its language bindings, as discussed in issue asticode/go-astilectron#193. It requires merging of PR asticode/go-astilectron#198 in order to work.

## Unsolved Issues

- [ ] Tell astilectron when the server is ready to connect.

# Changes

- Moved the bulk of code from `main.js` to `index.js`.

# index.js

- added `start(port: string)`, which starts astilectron.

## package.json

- Changed name from "Astilectron" to "astilectron" (see [name docs](https://docs.npmjs.com/files/package.json#name)).
- Added `main.js` to the `bin` field, because it is the cli entry point (see [bin docs](https://docs.npmjs.com/files/package.json#bin)).
- Added `index.js` to the `main` field, because it is the package entry point (see [main docs](https://docs.npmjs.com/files/package.json#main)).
- Added "license", "author" and "contributors" fields.
- moved `electron` from `devDependencies` to `peerDependencies` (see [peerDependencies docs](https://docs.npmjs.com/files/package.json#peerdependencies)).

## client.js

- `init()` now takes an optional "address" argument, which defaults to `process.argv[2]`.

2019-08-27 06:03 UTC, sbrow commented
Upon further inspection, I think it makes the most sense to leave it up to the end user to decide how to tell astilectron that go-astilectron is ready. That leaves it open in case other language bindings are ever created.

The alternative would be starting go-astilectron somewhere inside the `start()` function, and I'm not sure it makes sense to do that.

2019-09-12 09:30 UTC, asticode requested changes
My apologies for reviewing this PR so late.

2019-09-12 09:30 UTC, asticode commented on index.js
> +    client.emit(consts.eventNames.appCmdQuit);
I don't really see the point of adding this `emit` function if you use it only once

2019-09-12 09:30 UTC, asticode commented on src/client.js
> +    emit(eventName, payload) {
I don't really see the point of adding this `emit` function if you use it only once. Moreover I'd rather explicitly call the `write` function every time. Better remove this `emit` function.

2019-09-12 09:30 UTC, asticode commented on main.js
> +start(process.argv[0]);
This is the wrong arg number (it should be `2` instead of `0`). But since the `start` has it by default I would simply call `start()` here

2019-09-12 09:30 UTC, asticode commented on src/client.js
> +    init(addr = process.argv[2]) {
I like the fact that the `start` function has a default value for `addr` set to `process.argv[2]`. However I think this `init` function shouldn't have a default value.

2019-09-12 09:30 UTC, asticode commented on src/client.js
> +const consts = require('./consts');
If we remove the `emit` function, we can remove this line as well

2019-09-14 06:22 UTC, sbrow commented
> My apologies for reviewing this PR so late.

Don't worry about it :)

2019-09-17 07:27 UTC, merged

2019-09-17 07:31 UTC, asticode commented
FYI I've created a `0.33.0` tag. You'll need to update [this constant](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L23) accordingly.