Ensure element exists before trying to send message
asticode/astilectron pull request #42
Opened 2021-03-02 15:40 UTC by BillyMurrayOlive

If a request is in progress from a window when the window is closed, the response will cause an unhanded javascript exception popup. This PR avoids the unhandled exception by first checking that the element exists before accessing `webContents`.

2021-03-03 08:19 UTC, asticode requested changes
This makes lots of sense. One minor change needed though

2021-03-03 08:19 UTC, asticode commented on index.js
> +            if (targetElement) {
Could you one line this?

`if (targetElement) targetElement.webContents.send(json.name === consts.eventNames.windowCmdMessageCallback ? consts.eventNames.ipcCmdMessageCallback : consts.eventNames.ipcCmdMessage, m)`

2021-03-03 16:07 UTC, BillyMurrayOlive commented on index.js
> +            if (targetElement) {
Certainly! Just made the change.

2021-03-04 09:00 UTC, merged

2021-03-04 09:01 UTC, asticode commented
FYI I've created a `v0.45.0` tag

Cheers