Implement global shortcuts
asticode/astilectron pull request #66
Opened 2023-06-18 10:54 UTC by benebsiny

See https://github.com/asticode/go-astilectron/pull/393

2023-06-18 10:56 UTC, benebsiny commented
Off topic, won't it be a good idea to add tabs to the statements inside the `case`?

2023-08-17 08:15 UTC, asticode requested changes

2023-08-17 08:15 UTC, asticode commented on src/consts.js
> +        globalShortcutCmdRegister: "global.shortcut.cmd.register",
Could you make sure there's an `s` at the end of all `shortcut` occurrences?

2023-08-17 08:15 UTC, asticode commented on src/consts.js
> +        globalShortcutEventProcessFinished: "global.shortcut.event.process.finished",
Could you remove this event and instead use:

- `global.shortcuts.event.registered`
- `global.shortcuts.event.is.registered`
- `global.shortcuts.event.unregistered`
- `global.shortcuts.event.unregistered.all`

2023-08-17 08:15 UTC, asticode commented on index.js
> +            const isRegistered2 = globalShortcut.isRegistered(json.globalShortcut.accelerator);
No need to create a constant here, you can directly call:

```js
client.write(json.targetID, consts.eventNames.globalShortcutsEventIsRegistered, {globalShortcut:{isRegistered: globalShortcut.isRegistered(json.globalShortcut.accelerator)}});
```

2023-08-17 08:15 UTC, asticode commented on index.js
> +                client.write(json.targetID, consts.eventNames.globalShortcutEventTriggered, {GlobalShortcut:{accelerator: json.globalShortcut.accelerator}});
You need to use `globalShortcuts` instead of `GlobalShortcut` in the json

2023-09-03 10:21 UTC, asticode requested changes
Ping me when changes have been made 👍

2023-09-03 10:21 UTC, asticode commented on src/consts.js
> +        globalShortcutEventTriggered: "global.shortcuts.event.triggered",
We misunderstood each other: could you rollback all `globalShortcutCmd...` events but replace the `globalShortcutEventProcessFinished` with:

- global.shortcuts.event.
- global.shortcuts.event.is.
- global.shortcuts.event.
- global.shortcuts.event.unregistered.all

Also, could you make sure there's an `s` at the end of `globalShortcut` in the key?

This should look like this:

```javascript
globalShortcutsCmdRegister: "global.shortcuts.cmd.register",
globalShortcutsCmdIsRegistered: "global.shortcuts.cmd.is.register",
globalShortcutsCmdUnregister: "global.shortcuts.cmd.unregister",
globalShortcutsCmdUnregisterAll: "global.shortcuts.cmd.unregister.all",
globalShortcutsEventRegistered: "global.shortcuts.event.registered",
globalShortcutsEventIsRegistered: "global.shortcuts.event.is.registered",
globalShortcutsEventUnregistered: "global.shortcuts.event.unregistered",
globalShortcutsEventUnregisteredAll: "global.shortcuts.event.unregistered.all",
globalShortcutsEventProcessFinished: "global.shortcuts.event.process.finished",
globalShortcutsEventTriggered: "global.shortcuts.event.triggered",
```

2023-09-03 10:21 UTC, asticode commented on index.js
> +                client.write(json.targetID, consts.eventNames.globalShortcutEventTriggered, {GlobalShortcuts:{accelerator: json.globalShortcuts.accelerator}});
You need to use `globalShortcuts` with a lower `g` instead of `GlobalShortcuts` in the json. Same thing below

2023-12-15 08:27 UTC, asticode commented
👍 I'll merge this PR once its GO counter-part is OK

> Off topic, won't it be a good idea to add tabs to the statements inside the case?

If you feel like it, that would be a good idea indeed 👍

2023-12-21 08:05 UTC, merged

2023-12-21 08:05 UTC, asticode commented
Thanks for the PR! ❤️